# Generated by Django 3.2 on 2021-05-05 16:25

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='usuario',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('run', models.CharField(max_length=10)),
                ('nombre', models.CharField(max_length=30)),
                ('email', models.EmailField(max_length=20)),
                ('telefono', models.CharField(max_length=20)),
                ('mensaje', models.TextField()),
            ],
            options={
                'db_table': 'usuario',
                'ordering': ['run'],
            },
        ),
    ]
